cpufreq_elementalx: initial release for tegra
conflict cpufreq_governor.c

Notes:
i may have fixed it
had to remove sampling_rate
from line 92

drivers/cpufreq/cpufreq_governor.c: In function 'dbs_check_cpu':
drivers/cpufreq/cpufreq_governor.c:92:3: error: 'sampling_rate' undeclared (first use in this function)
   sampling_rate = cs_tuners->sampling_rate;
   ^
drivers/cpufreq/cpufreq_governor.c:92:3: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:308: recipe for target 'drivers/cpufreq/cpufreq_governor.o' failed
make[2]: *** [drivers/cpufreq/cpufreq_governor.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/cpufreq' failed
make[1]: *** [drivers/cpufreq] Error 2
Makefile:804: recipe for target 'drivers' failed
make: *** [drivers] Error 2
make: *** Waiting for unfinished jobs....

Conflicts:
	drivers/cpufreq/cpufreq_governor.c